name: Build Next.js site

on:
  pull_request:
  workflow_call:
    inputs:
      should-upload-artifact:
        required: false
        type: boolean
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: "24"
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Pages
        uses: actions/configure-pages@v6
        with:
          # Automatically inject basePath in your Next.js configuration file and disable
          # server side image optimization (https://nextjs.org/docs/api-reference/next/image#unoptimized).
          #
          # You may remove this line if you want to manage the configuration yourself.
          static_site_generator: next
      - name: Install dependencies
        run: yarn install --immutable
      - name: Lint with Biome
        run: yarn lint
      - name: Test fixtures
        run: yarn test
      - name: Telemetry Opt-Out
        run: yarn next telemetry disable
      - name: Build with Next.js
        run: yarn build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        if: ${{ inputs.should-upload-artifact }}
        with:
          path: ./dist
